"""Export the generated chapter files as one audiobook file."""

import os
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Iterable, Optional


def _concat_manifest_entry(path: Path) -> str:
    """Return an ffmpeg concat-demuxer entry safe for paths with spaces/quotes."""
    value = str(path.resolve()).replace("\\", "\\\\").replace("'", "'\\''")
    return f"file '{value}'"


def export_final_m4a(
    audio_files: Iterable[str | Path],
    output_folder: str | Path,
    title: Optional[str] = None,
    author: Optional[str] = None,
) -> Path:
    """Concatenate chapter audio files into ``output_folder/final/*.m4a``.

    FFmpeg performs the concatenation and AAC encoding as a stream, avoiding
    loading an entire long book into Python memory. The source chapter files
    are intentionally kept for recovery/debugging; the ``final`` folder is
    the user-facing single-file result.
    """
    files = [Path(path).expanduser().resolve() for path in audio_files]
    if not files:
        raise ValueError("No chapter audio files were provided for final export.")
    missing = [str(path) for path in files if not path.is_file()]
    if missing:
        raise FileNotFoundError(
            "Missing chapter audio files: " + ", ".join(missing[:5])
        )

    ffmpeg = shutil.which("ffmpeg")
    if not ffmpeg:
        raise RuntimeError("FFmpeg is required to create the final M4A file.")

    output_root = Path(output_folder).expanduser().resolve()
    final_folder = output_root / "final"
    final_folder.mkdir(parents=True, exist_ok=True)
    final_path = final_folder / f"{output_root.name}.m4a"
    # Keep .m4a as the final suffix so FFmpeg selects the MP4/M4A muxer.
    temporary_output = final_folder / f".{output_root.name}.tmp.m4a"

    manifest_path = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w", encoding="utf-8", suffix=".ffconcat", delete=False
        ) as manifest:
            manifest_path = Path(manifest.name)
            manifest.write("# generated by epub_to_audiobook\n")
            manifest.write("\n".join(_concat_manifest_entry(path) for path in files))
            manifest.write("\n")

        command = [
            ffmpeg,
            "-hide_banner",
            "-loglevel",
            "error",
            "-y",
            "-f",
            "concat",
            "-safe",
            "0",
            "-i",
            str(manifest_path),
            "-map",
            "0:a:0",
            "-vn",
            "-c:a",
            "aac",
            "-b:a",
            "128k",
            "-ar",
            "44100",
            "-ac",
            "1",
            "-movflags",
            "+faststart",
        ]
        if title:
            command.extend(["-metadata", f"title={title}"])
        if author:
            command.extend(["-metadata", f"artist={author}"])
        command.extend(["-metadata", "comment=Generated as a single audiobook file"])
        command.append(str(temporary_output))

        result = subprocess.run(
            command,
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        if result.returncode != 0:
            detail = (result.stderr or "FFmpeg returned an unknown error").strip()
            raise RuntimeError(f"FFmpeg failed while creating final M4A: {detail[-4000:]}")

        os.replace(temporary_output, final_path)
        return final_path
    finally:
        if manifest_path and manifest_path.exists():
            manifest_path.unlink()
        if temporary_output.exists():
            temporary_output.unlink()
